// <auto-generated />
using System;
using Ef_Project;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ef_Project.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260308123653_AssignDepartmentManagers")]
    partial class AssignDepartmentManagers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ef_Project.Models.Course", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<int?>("InstructorID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("InstructorID");

                    b.ToTable("Course", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DepartmentID = 1,
                            Duration = 40,
                            InstructorID = 1,
                            Name = "C# Fundamentals"
                        },
                        new
                        {
                            ID = 2,
                            DepartmentID = 1,
                            Duration = 30,
                            InstructorID = 3,
                            Name = "Database Systems"
                        },
                        new
                        {
                            ID = 3,
                            DepartmentID = 2,
                            Duration = 25,
                            InstructorID = 2,
                            Name = "Linear Algebra"
                        });
                });

            modelBuilder.Entity("Ef_Project.Models.CourseSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("InstructorID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CourseID");

                    b.HasIndex("InstructorID");

                    b.ToTable("CourseSession", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseID = 1,
                            Date = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorID = 1,
                            Title = "Intro to C#"
                        },
                        new
                        {
                            Id = 2,
                            CourseID = 1,
                            Date = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorID = 1,
                            Title = "OOP Basics"
                        },
                        new
                        {
                            Id = 3,
                            CourseID = 2,
                            Date = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorID = 3,
                            Title = "SQL Joins"
                        },
                        new
                        {
                            Id = 4,
                            CourseID = 3,
                            Date = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorID = 2,
                            Title = "Matrix Operations"
                        });
                });

            modelBuilder.Entity("Ef_Project.Models.CourseSessionAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseSessionId")
                        .HasColumnType("int");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(max)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseSessionId");

                    b.HasIndex("StudentID");

                    b.ToTable("CourseSessionAttendance", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseSessionId = 1,
                            Grade = 85,
                            Notes = "Good",
                            StudentID = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseSessionId = 1,
                            Grade = 90,
                            Notes = "Excellent",
                            StudentID = 2
                        },
                        new
                        {
                            Id = 3,
                            CourseSessionId = 2,
                            Grade = 78,
                            StudentID = 1
                        },
                        new
                        {
                            Id = 4,
                            CourseSessionId = 3,
                            Grade = 88,
                            Notes = "Well done",
                            StudentID = 3
                        },
                        new
                        {
                            Id = 5,
                            CourseSessionId = 4,
                            Grade = 92,
                            Notes = "Outstanding",
                            StudentID = 2
                        });
                });

            modelBuilder.Entity("Ef_Project.Models.CourseStudent", b =>
                {
                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("CourseID", "StudentID");

                    b.HasIndex("StudentID");

                    b.ToTable("Course_Student", (string)null);

                    b.HasData(
                        new
                        {
                            CourseID = 1,
                            StudentID = 1
                        },
                        new
                        {
                            CourseID = 1,
                            StudentID = 2
                        },
                        new
                        {
                            CourseID = 2,
                            StudentID = 1
                        },
                        new
                        {
                            CourseID = 2,
                            StudentID = 3
                        },
                        new
                        {
                            CourseID = 3,
                            StudentID = 2
                        });
                });

            modelBuilder.Entity("Ef_Project.Models.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ManagerID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("DepartmentID");

                    b.HasIndex("ManagerID")
                        .IsUnique()
                        .HasFilter("[ManagerID] IS NOT NULL");

                    b.ToTable("Department", (string)null);

                    b.HasData(
                        new
                        {
                            DepartmentID = 1,
                            Location = "Building A",
                            ManagerID = 1,
                            Name = "Computer Science"
                        },
                        new
                        {
                            DepartmentID = 2,
                            Location = "Building B",
                            ManagerID = 2,
                            Name = "Mathematics"
                        });
                });

            modelBuilder.Entity("Ef_Project.Models.Instructor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Instructor");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DepartmentID = 1,
                            FirstName = "Ahmed",
                            LastName = "Ali",
                            Phone = "0100000001"
                        },
                        new
                        {
                            ID = 2,
                            DepartmentID = 2,
                            FirstName = "Sara",
                            LastName = "Hassan",
                            Phone = "0100000002"
                        },
                        new
                        {
                            ID = 3,
                            DepartmentID = 1,
                            FirstName = "Mohamed",
                            LastName = "Saeed",
                            Phone = "0100000003"
                        });
                });

            modelBuilder.Entity("Ef_Project.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FirstName = "Omar",
                            LastName = "Khaled",
                            Phone = "0110000001"
                        },
                        new
                        {
                            ID = 2,
                            FirstName = "Nora",
                            LastName = "Youssef",
                            Phone = "0110000002"
                        },
                        new
                        {
                            ID = 3,
                            FirstName = "Ali",
                            LastName = "Mostafa",
                            Phone = "0110000003"
                        });
                });

            modelBuilder.Entity("Ef_Project.Models.Course", b =>
                {
                    b.HasOne("Ef_Project.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ef_Project.Models.Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Ef_Project.Models.CourseSession", b =>
                {
                    b.HasOne("Ef_Project.Models.Course", "Course")
                        .WithMany("CourseSessions")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ef_Project.Models.Instructor", "Instructor")
                        .WithMany("CourseSessions")
                        .HasForeignKey("InstructorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Ef_Project.Models.CourseSessionAttendance", b =>
                {
                    b.HasOne("Ef_Project.Models.CourseSession", "CourseSession")
                        .WithMany("Attendances")
                        .HasForeignKey("CourseSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ef_Project.Models.Student", "Student")
                        .WithMany("CourseSessionAttendances")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseSession");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Ef_Project.Models.CourseStudent", b =>
                {
                    b.HasOne("Ef_Project.Models.Course", "Course")
                        .WithMany("CourseStudents")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ef_Project.Models.Student", "Student")
                        .WithMany("CourseStudents")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Ef_Project.Models.Department", b =>
                {
                    b.HasOne("Ef_Project.Models.Instructor", "Manager")
                        .WithOne("ManagedDepartment")
                        .HasForeignKey("Ef_Project.Models.Department", "ManagerID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Ef_Project.Models.Instructor", b =>
                {
                    b.HasOne("Ef_Project.Models.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Ef_Project.Models.Course", b =>
                {
                    b.Navigation("CourseSessions");

                    b.Navigation("CourseStudents");
                });

            modelBuilder.Entity("Ef_Project.Models.CourseSession", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("Ef_Project.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("Ef_Project.Models.Instructor", b =>
                {
                    b.Navigation("CourseSessions");

                    b.Navigation("Courses");

                    b.Navigation("ManagedDepartment");
                });

            modelBuilder.Entity("Ef_Project.Models.Student", b =>
                {
                    b.Navigation("CourseSessionAttendances");

                    b.Navigation("CourseStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
